apiVersion: v1
kind: ConfigMap
metadata:
  name: apisix-config
  namespace: peopleportal
data:
  config.yaml: |
    apisix:
      node_listen: 9080
      enable_admin: true
      admin_api:
        listen: "0.0.0.0:9180"

    deployment:
      role: traditional
      role_traditional:
        config_provider: yaml
      admin:
        admin_key:
          - name: "admin"
            key: "edd1c9f034335f136f87ad84b625c8f1"
            role: admin

    routes:
      - uri: /api/requests*
        name: requests-api
        methods: ["GET", "POST", "PATCH"]
        plugins:
          openid-connect:
            client_id: "peopleportal-api"
            client_secret: "fXvEaUeieNd3taTylb0LbBY4npbISmXC"
            discovery: "http://keycloak-service:8080/realms/peopleportal/.well-known/openid-configuration"
            scope: "openid profile email"
            bearer_only: true
            realm: "peopleportal"
            session:
              secret: "peopleportal-session-secret-2026"
        upstream:
          type: roundrobin
          nodes:
            "peopleportal-api-service:80": 1

      - uri: /api/hr*
        name: hr-api
        methods: ["GET", "POST", "PATCH"]
        plugins:
          openid-connect:
            client_id: "peopleportal-api"
            client_secret: "fXvEaUeieNd3taTylb0LbBY4npbISmXC"
            discovery: "http://keycloak-service:8080/realms/peopleportal/.well-known/openid-configuration"
            scope: "openid profile email"
            bearer_only: true
            realm: "peopleportal"
        upstream:
          type: roundrobin
          nodes:
            "peopleportal-api-service:80": 1

      - uri: /api/employees*
        name: employees-api
        methods: ["GET", "PUT", "POST"]
        plugins:
          openid-connect:
            client_id: "peopleportal-api"
            client_secret: "fXvEaUeieNd3taTylb0LbBY4npbISmXC"
            discovery: "http://keycloak-service:8080/realms/peopleportal/.well-known/openid-configuration"
            scope: "openid profile email"
            bearer_only: true
            realm: "peopleportal"
        upstream:
          type: roundrobin
          nodes:
            "peopleportal-api-service:80": 1

      - uri: /api/documents*
        name: documents-api
        methods: ["GET", "POST", "PATCH"]
        plugins:
          openid-connect:
            client_id: "peopleportal-api"
            client_secret: "fXvEaUeieNd3taTylb0LbBY4npbISmXC"
            discovery: "http://keycloak-service:8080/realms/peopleportal/.well-known/openid-configuration"
            scope: "openid profile email"
            bearer_only: true
            realm: "peopleportal"
        upstream:
          type: roundrobin
          nodes:
            "peopleportal-api-service:80": 1

      - uri: /api/announcements*
        name: announcements-api
        methods: ["GET", "POST"]
        plugins:
          openid-connect:
            client_id: "peopleportal-api"
            client_secret: "fXvEaUeieNd3taTylb0LbBY4npbISmXC"
            discovery: "http://keycloak-service:8080/realms/peopleportal/.well-known/openid-configuration"
            scope: "openid profile email"
            bearer_only: true
            realm: "peopleportal"
        upstream:
          type: roundrobin
          nodes:
            "peopleportal-api-service:80": 1

      - uri: /api/benefits*
        name: benefits-api
        methods: ["GET"]
        plugins:
          openid-connect:
            client_id: "peopleportal-api"
            client_secret: "fXvEaUeieNd3taTylb0LbBY4npbISmXC"
            discovery: "http://keycloak-service:8080/realms/peopleportal/.well-known/openid-configuration"
            scope: "openid profile email"
            bearer_only: true
            realm: "peopleportal"
        upstream:
          type: roundrobin
          nodes:
            "peopleportal-api-service:80": 1

      - uri: /api/dashboard*
        name: dashboard-api
        methods: ["GET"]
        plugins:
          openid-connect:
            client_id: "peopleportal-api"
            client_secret: "fXvEaUeieNd3taTylb0LbBY4npbISmXC"
            discovery: "http://keycloak-service:8080/realms/peopleportal/.well-known/openid-configuration"
            scope: "openid profile email"
            bearer_only: true
            realm: "peopleportal"
        upstream:
          type: roundrobin
          nodes:
            "peopleportal-api-service:80": 1

      - uri: /api/manager*
        name: manager-api
        methods: ["GET", "PATCH"]
        plugins:
          openid-connect:
            client_id: "peopleportal-api"
            client_secret: "fXvEaUeieNd3taTylb0LbBY4npbISmXC"
            discovery: "http://keycloak-service:8080/realms/peopleportal/.well-known/openid-configuration"
            scope: "openid profile email"
            bearer_only: true
            realm: "peopleportal"
        upstream:
          type: roundrobin
          nodes:
            "peopleportal-api-service:80": 1

      - uri: /health
        name: health-api
        methods: ["GET"]
        upstream:
          type: roundrobin
          nodes:
            "peopleportal-api-service:80": 1

      - uri: /swagger/*
        name: swagger-api
        methods: ["GET"]
        upstream:
          type: roundrobin
          nodes:
            "peopleportal-api-service:80": 1
