apiVersion: v1
kind: ConfigMap
metadata:
  name: apisix-config
  namespace: peopleportal
data:
  config.yaml: |
    apisix:
      node_listen: 9080
      enable_admin: false

    deployment:
      role: traditional
      role_traditional:
        config_provider: yaml
