apiVersion: v1
data:
  keycloak-realm.json: |
    {
      "realm": "peopleportal",
      "enabled": true,
      "displayName": "PeoplePortal",
      "sslRequired": "external",
      "registrationAllowed": false,
      "loginWithEmailAllowed": true,
      "resetPasswordAllowed": true,
      "roles": {
        "realm": [
          { "name": "employee", "description": "Colaborador" },
          { "name": "jefe_inmediato", "description": "Jefe inmediato" },
          { "name": "hr", "description": "Recursos Humanos" },
          { "name": "nomina", "description": "NÔö£Ôöémina" },
          { "name": "admin", "description": "Administrador" }
        ]
      },
      "clients": [
        {
          "clientId": "peopleportal-frontend",
          "enabled": true,
          "publicClient": true,
          "protocol": "openid-connect",
          "standardFlowEnabled": true,
          "implicitFlowEnabled": false,
          "directAccessGrantsEnabled": true,
          "redirectUris": [
            "http://localhost:5173/*",
            "http://localhost:5174/*",
            "http://localhost:30081/*",
            "http://localhost:30082/*",
            "http://localhost:4200/*",
            "http://localhost:3000/*"
          ],
          "webOrigins": [
            "http://localhost:5173",
            "http://localhost:5174",
            "http://localhost:30081",
            "http://localhost:30082",
            "http://localhost:4200",
            "http://localhost:3000"
          ],
          "attributes": {
            "pkce.code.challenge.method": "S256",
            "post.logout.redirect.uris": "http://localhost:30081/*##http://localhost:30082/*"
          },
          "protocolMappers": [
            {
              "name": "audience-peopleportal-api",
              "protocol": "openid-connect",
              "protocolMapper": "oidc-audience-mapper",
              "consentRequired": false,
              "config": {
                "id.token.claim": "false",
                "access.token.claim": "true",
                "included.client.audience": "peopleportal-api"
              }
            }
          ]
        },
        {
          "clientId": "peopleportal-api",
          "enabled": true,
          "publicClient": false,
          "protocol": "openid-connect",
          "bearerOnly": true,
          "standardFlowEnabled": false,
          "directAccessGrantsEnabled": false
        }
      ],
      "users": [
        {
          "id": "2ec78c39-d293-4bdd-9ff0-2d9ce163a8fd", "username": "testuser",
          "enabled": true,
          "email": "testuser@peopleportal.local",
          "firstName": "Test",
          "lastName": "User",
          "emailVerified": true,
          "credentials": [
            {
              "type": "password",
              "value": "test123",
              "temporary": false
            }
          ],
          "realmRoles": ["employee"]
        },
        {
          "id": "e8f232a5-a95a-45e1-b542-5240b3577094", "username": "testmanager",
          "enabled": true,
          "email": "testmanager@peopleportal.local",
          "firstName": "Test",
          "lastName": "Manager",
          "emailVerified": true,
          "credentials": [
            {
              "type": "password",
              "value": "test123",
              "temporary": false
            }
          ],
          "realmRoles": ["employee", "jefe_inmediato"]
        },
        {
          "id": "59612e29-6b6c-4159-b970-be79df3c95a2", "username": "testhr",
          "enabled": true,
          "email": "testhr@peopleportal.local",
          "firstName": "Test",
          "lastName": "HR",
          "emailVerified": true,
          "credentials": [
            {
              "type": "password",
              "value": "test123",
              "temporary": false
            }
          ],
          "realmRoles": ["employee", "hr"]
        },
        {
          "id": "29e218c9-a768-491c-84ae-81cd0677eaaa", "username": "admin",
          "enabled": true,
          "email": "admin@peopleportal.local",
          "firstName": "PeoplePortal",
          "lastName": "Admin",
          "emailVerified": true,
          "credentials": [
            {
              "type": "password",
              "value": "admin123",
              "temporary": false
            }
          ],
          "realmRoles": ["employee", "admin"]
        }
      ]
    }
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"keycloak-realm.json":"{\n  \"realm\": \"peopleportal\",\n  \"enabled\": true,\n  \"displayName\": \"PeoplePortal\",\n  \"sslRequired\": \"external\",\n  \"registrationAllowed\": false,\n  \"loginWithEmailAllowed\": true,\n  \"resetPasswordAllowed\": true,\n  \"roles\": {\n    \"realm\": [\n      { \"name\": \"employee\", \"description\": \"Colaborador\" },\n      { \"name\": \"jefe_inmediato\", \"description\": \"Jefe inmediato\" },\n      { \"name\": \"hr\", \"description\": \"Recursos Humanos\" },\n      { \"name\": \"nomina\", \"description\": \"NÔö£Ôöémina\" },\n      { \"name\": \"admin\", \"description\": \"Administrador\" }\n    ]\n  },\n  \"clients\": [\n    {\n      \"clientId\": \"peopleportal-frontend\",\n      \"enabled\": true,\n      \"publicClient\": true,\n      \"protocol\": \"openid-connect\",\n      \"standardFlowEnabled\": true,\n      \"implicitFlowEnabled\": false,\n      \"directAccessGrantsEnabled\": true,\n      \"redirectUris\": [\n        \"http://localhost:5173/*\",\n        \"http://localhost:5174/*\",\n        \"http://localhost:30081/*\",\n        \"http://localhost:30082/*\",\n        \"http://localhost:4200/*\",\n        \"http://localhost:3000/*\"\n      ],\n      \"webOrigins\": [\n        \"http://localhost:5173\",\n        \"http://localhost:5174\",\n        \"http://localhost:30081\",\n        \"http://localhost:30082\",\n        \"http://localhost:4200\",\n        \"http://localhost:3000\"\n      ],\n      \"attributes\": {\n        \"pkce.code.challenge.method\": \"S256\",\n        \"post.logout.redirect.uris\": \"http://localhost:30081/*\"\n      },\n      \"protocolMappers\": [\n        {\n          \"name\": \"audience-peopleportal-api\",\n          \"protocol\": \"openid-connect\",\n          \"protocolMapper\": \"oidc-audience-mapper\",\n          \"consentRequired\": false,\n          \"config\": {\n            \"id.token.claim\": \"false\",\n            \"access.token.claim\": \"true\",\n            \"included.client.audience\": \"peopleportal-api\"\n          }\n        }\n      ]\n    },\n    {\n      \"clientId\": \"peopleportal-api\",\n      \"enabled\": true,\n      \"publicClient\": false,\n      \"protocol\": \"openid-connect\",\n      \"bearerOnly\": true,\n      \"standardFlowEnabled\": false,\n      \"directAccessGrantsEnabled\": false\n    }\n  ],\n  \"users\": [\n    {\n      \"username\": \"testuser\",\n      \"enabled\": true,\n      \"email\": \"testuser@peopleportal.local\",\n      \"firstName\": \"Test\",\n      \"lastName\": \"User\",\n      \"emailVerified\": true,\n      \"credentials\": [\n        {\n          \"type\": \"password\",\n          \"value\": \"test123\",\n          \"temporary\": false\n        }\n      ],\n      \"realmRoles\": [\"employee\"]\n    },\n    {\n      \"username\": \"testmanager\",\n      \"enabled\": true,\n      \"email\": \"testmanager@peopleportal.local\",\n      \"firstName\": \"Test\",\n      \"lastName\": \"Manager\",\n      \"emailVerified\": true,\n      \"credentials\": [\n        {\n          \"type\": \"password\",\n          \"value\": \"test123\",\n          \"temporary\": false\n        }\n      ],\n      \"realmRoles\": [\"employee\", \"jefe_inmediato\"]\n    },\n    {\n      \"username\": \"testhr\",\n      \"enabled\": true,\n      \"email\": \"testhr@peopleportal.local\",\n      \"firstName\": \"Test\",\n      \"lastName\": \"HR\",\n      \"emailVerified\": true,\n      \"credentials\": [\n        {\n          \"type\": \"password\",\n          \"value\": \"test123\",\n          \"temporary\": false\n        }\n      ],\n      \"realmRoles\": [\"employee\", \"hr\"]\n    },\n    {\n      \"username\": \"admin\",\n      \"enabled\": true,\n      \"email\": \"admin@peopleportal.local\",\n      \"firstName\": \"PeoplePortal\",\n      \"lastName\": \"Admin\",\n      \"emailVerified\": true,\n      \"credentials\": [\n        {\n          \"type\": \"password\",\n          \"value\": \"admin123\",\n          \"temporary\": false\n        }\n      ],\n      \"realmRoles\": [\"employee\", \"admin\"]\n    }\n  ]\n}\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"keycloak-realm","namespace":"peopleportal"}}
  creationTimestamp: "2026-06-29T23:43:51Z"
  name: keycloak-realm
  namespace: peopleportal
  resourceVersion: "29956"
  uid: 43d67771-ffe6-42cb-9a81-f230f3b123aa

