apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Infraestructura global: no tiene imágenes con variación por entorno
# Los deployments con imagen (api, frontends) se gestionan en cada submodulo
resources:
  - namespace.yaml
  - secret.yaml
  - keycloak-realm-configmap.yaml
  - keycloak.yaml
  - apisix-configmap.yaml
  - apisix.yaml
