apiVersion: v1
kind: Secret
metadata:
  name: peopleportal-secrets
  namespace: peopleportal
type: Opaque
stringData:
  POSTGRES_PASSWORD: "YourStrong@Passw0rd"
  ConnectionStrings__DefaultConnection: "Host=postgres-service;Port=5432;Database=PeoplePortalDb;Username=postgres;Password=YourStrong@Passw0rd;"
  Keycloak__AdminPassword: "admin"
  KeycloakAdmin__AdminPassword: "admin"
